# Generated by Django 5.2 on 2025-04-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('debut_Pdc', models.DateField()),
                ('Fin_Pdc', models.DateField()),
                ('statut', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='client.client')),
                ('equipe', models.ManyToManyField(related_name='projets', to='equipe.equipe')),
            ],
        ),
    ]
