# Generated by Django 5.2 on 2025-05-19 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('projet_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('ordre_travail', models.CharField(blank=True, max_length=50, null=True)),
                ('direct_client', models.CharField(max_length=255)),
                ('final_client', models.CharField(max_length=255)),
                ('sop', models.CharField(choices=[('Interne', 'Interne'), ('Externe', 'Externe')], max_length=10)),
                ('ibu', models.CharField(blank=True, max_length=100, null=True)),
                ('cbu', models.CharField(blank=True, max_length=50, null=True)),
                ('date_demarrage', models.DateField()),
                ('chef_de_projet', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif')], default='Actif', max_length=10)),
                ('descriptif', models.TextField()),
                ('tl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projets_tl', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
