# Generated by Django 5.2 on 2025-05-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='Fin_Pdc',
            new_name='date_debut',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='debut_Pdc',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='equipe',
        ),
        migrations.AddField(
            model_name='projet',
            name='chef',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projet',
            name='nom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projet',
            name='wo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='client',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Passif', 'Passif')], default='Actif', max_length=50),
        ),
    ]
