# Generated by Django 5.2 on 2025-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='descriptif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Closed', 'Closed')], default='In Progress', max_length=12),
        ),
    ]
