# Generated by Django 5.2 on 2025-07-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_alter_projet_code_alter_projet_descriptif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='final_client',
        ),
    ]
