# Generated by Django 5.2 on 2025-07-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_remove_projet_final_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='direct_client',
            new_name='final_client',
        ),
    ]
