# Generated by Django 5.2 on 2025-04-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('personne', models.ManyToManyField(related_name='fonctions', to='personne.personne')),
            ],
        ),
    ]
