# Generated by Django 5.2 on 2025-04-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(max_length=50)),
                ('manager_superieur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers_subordonnes', to='manager.manager')),
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personne.personne')),
            ],
        ),
    ]
