# Generated by Django 5.2 on 2025-06-02 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='equipes',
            field=models.ManyToManyField(blank=True, null=True, related_name='domains', to='formation.equipe'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='image_cover',
            field=models.ImageField(blank=True, null=True, upload_to='domains/'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='equipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='image_cover',
            field=models.ImageField(blank=True, null=True, upload_to='formations/'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='modules',
            field=models.ManyToManyField(blank=True, null=True, related_name='formations', to='formation.module'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='ressources',
            field=models.ManyToManyField(blank=True, null=True, related_name='formations', to='formation.resource'),
        ),
        migrations.AlterField(
            model_name='module',
            name='estimated_time',
            field=models.DurationField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='module',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='modules/videos/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
