# Generated by Django 5.2 on 2025-06-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_alter_domain_equipes_alter_domain_image_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='video',
            field=models.FileField(upload_to='modules/videos/'),
        ),
    ]
