# Generated by Django 5.2 on 2025-06-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_alter_module_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz/questions/'),
        ),
    ]
