# Generated by Django 5.2 on 2025-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_question_correct_keywords_question_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='resource',
            name='allowed_equipes',
            field=models.ManyToManyField(blank=True, related_name='resources_access', to='formation.equipe'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='estimated_time',
            field=models.DurationField(default='00:00:00'),
        ),
    ]
