# Generated by Django 5.2 on 2025-06-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_remove_resource_allowed_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformation',
            name='completed_steps',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
