# Generated by Django 5.2 on 2025-07-03 13:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0007_remove_domain_image_cover_domain_consultant_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='consultant_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='domain',
            name='leader_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='domain',
            name='prerequisites_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
