# Generated by Django 5.2 on 2025-07-07 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0008_alter_domain_consultant_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformation',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userformation',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
