# Generated by Django 5.2 on 2025-07-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0010_alter_useranswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='formateur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
