# Generated by Django 5.2 on 2025-07-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0012_userquizhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Nombre maximal de tentatives autorisées. Laissez vide pour illimité.', null=True),
        ),
    ]
