# Generated by Django 5.2 on 2025-07-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0013_quiz_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='attempts_made',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
