# Generated by Django 5.2 on 2025-08-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0014_userquiz_attempts_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='image_response',
        ),
    ]
