# Generated by Django 5.2 on 2025-05-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('matricule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dt_Embauche', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('N1', 'Team Leader N1'), ('N2', 'Team Leader N2'), ('COLLABORATEUR', 'Collaborateur')], max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('password', models.CharField(default='default_password', max_length=128)),
                ('cv', models.ImageField(blank=True, null=True, upload_to='cvs/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
