# Generated by Django 5.2 on 2025-05-19 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('matricule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('sexe', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=14, null=True)),
                ('role', models.CharField(choices=[('TL1', 'Team Leader N1'), ('TL2', 'Team Leader N2'), ('COLLABORATEUR', 'Collaborateur')], max_length=100)),
                ('dt_Debut_Carriere', models.DateField(blank=True, null=True)),
                ('experience_total', models.IntegerField(default=0)),
                ('dt_Embauche', models.DateField()),
                ('experience_expleo', models.IntegerField(default=0)),
                ('position', models.CharField(choices=[('I1', 'I1'), ('I2', 'I2'), ('I3', 'I3'), ('I4', 'I4'), ('I5', 'I5'), ('I6', 'I6'), ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], default='T1', max_length=100)),
                ('diplome', models.CharField(blank=True, choices=[('Bac+2', 'Bac+2'), ('Bac+3', 'Bac+3'), ('Bac+5', 'Bac+5')], max_length=100, null=True)),
                ('specialite_diplome', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('En formation', 'En formation'), ('En cours', 'En cours'), ('Bench', 'Bench'), ('Out', 'Out'), ('Management', 'Management'), ('Stage', 'Stage')], default='En cours', max_length=20)),
                ('ddc', models.FileField(blank=True, null=True, upload_to='ddc/')),
                ('password', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_persons', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
