# Generated by Django 5.2 on 2025-04-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('matricule', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('dt_Embauche', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('motDePasse', models.CharField(max_length=255)),
                ('cv', models.ImageField(blank=True, null=True, upload_to='cvs/')),
            ],
        ),
    ]
