# Generated by Django 5.2 on 2025-04-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='motDePasse',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='prenom',
        ),
        migrations.AddField(
            model_name='personne',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='personne',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.CharField(choices=[('N1', 'Team Leader N1'), ('N2', 'Team Leader N2'), ('COLLABORATEUR', 'Collaborateur')], max_length=100),
        ),
    ]
