# Generated by Django 5.2 on 2025-05-06 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personne',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='personne',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='personne',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
