# Generated by Django 5.2 on 2025-07-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='i_e',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Extern', 'Extern')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
