# Generated by Django 5.2 on 2025-05-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0002_personne_date_joined_personne_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
