# Generated by Django 5.2 on 2025-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0002_remove_personne_email_remove_personne_motdepasse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personne',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
