# Generated by Django 5.2 on 2025-07-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0003_personne_i_e_personne_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='i_e',
        ),
    ]
