# Generated by Django 5.2 on 2025-05-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0003_remove_personne_is_staff_alter_personne_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personne',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
