# Generated by Django 5.2 on 2025-07-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0004_remove_personne_i_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='excels/')),
                ('importé_le', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
