# Generated by Django 5.2 on 2025-05-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0004_personne_is_staff_alter_personne_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
