# Generated by Django 5.2 on 2025-05-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0005_personne_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='I_E',
            field=models.CharField(choices=[('Intern', 'Intern'), ('Extern', 'Extern')], default='Intern', max_length=10),
        ),
        migrations.AddField(
            model_name='personne',
            name='status',
            field=models.CharField(choices=[('En formation', 'En formation'), ('En cours', 'En cours'), ('Bench', 'Bench'), ('Out', 'Out'), ('Management', 'Management'), ('Stage', 'Stage')], default='En cours', max_length=20),
        ),
    ]
