# Generated by Django 5.2 on 2025-07-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0005_importedexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.CharField(choices=[('TL1', 'Team Leader N1'), ('TL2', 'Team Leader N2'), ('COLLABORATEUR', 'Collaborateur'), ('CL', 'Country Leader'), ('UDL', 'Unit Delivery Leader')], max_length=100),
        ),
    ]
