# Generated by Django 5.2 on 2025-09-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0006_alter_personne_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='position',
            field=models.CharField(choices=[('I1', 'I1'), ('I2', 'I2'), ('I3', 'I3'), ('I4', 'I4'), ('I5', 'I5'), ('I6', 'I6'), ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6'), ('N/A', 'Non applicable')], default='T1', max_length=100),
        ),
    ]
