# Generated by Django 5.2 on 2025-05-09 09:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0006_personne_i_e_personne_status'),
        ('projet', '0002_rename_id_projet_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='I_E',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='personne',
            name='backup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_persons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personne',
            name='ddc',
            field=models.FileField(blank=True, null=True, upload_to='ddc/'),
        ),
        migrations.AddField(
            model_name='personne',
            name='deplome',
            field=models.CharField(choices=[('Bac+2', 'Bac+2'), ('Bac+3', 'Bac+3'), ('Bac+5', 'Bac+5')], default='Bac+2', max_length=100),
        ),
        migrations.AddField(
            model_name='personne',
            name='dt_Debut_Carriere',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='personne',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_persons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personne',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projet_persons', to='projet.projet'),
        ),
        migrations.AddField(
            model_name='personne',
            name='specialite_deplome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personne',
            name='dt_Embauche',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='personne',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='personne',
            name='position',
            field=models.CharField(choices=[('I1', 'I1'), ('I2', 'I2'), ('I3', 'I3'), ('I4', 'I4'), ('I5', 'I5'), ('I6', 'I6'), ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], default='T1', max_length=100),
        ),
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.CharField(choices=[('TL1', 'Team Leader N1'), ('TL2', 'Team Leader N2'), ('COLLABORATEUR', 'Collaborateur')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personne',
            name='telephone',
            field=models.CharField(max_length=14),
        ),
    ]
