# Generated by Django 5.2 on 2025-05-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0007_remove_personne_i_e_remove_personne_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='password',
            field=models.CharField(default=models.CharField(max_length=50, primary_key=True, serialize=False), max_length=128),
        ),
    ]
