# Generated by Django 5.2 on 2025-05-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0008_alter_personne_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='experience_expleo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personne',
            name='experience_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personne',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
