# Generated by Django 5.2 on 2025-05-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0009_personne_experience_expleo_personne_experience_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personne',
            old_name='deplome',
            new_name='diplome',
        ),
    ]
