# Generated by Django 5.2 on 2025-05-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0010_rename_deplome_personne_diplome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personne',
            old_name='specialite_deplome',
            new_name='specialite_diplome',
        ),
    ]
