# Generated by Django 5.2 on 2025-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personne', '0011_rename_specialite_deplome_personne_specialite_diplome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='dt_Debut_Carriere',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='dt_Embauche',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='personne',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='personne',
            name='specialite_diplome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='telephone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
